#!/usr/bin/env node
/**
 * Generates extension/config.js from the appropriate .env file.
 *
 * Usage:
 *   node build.js                  # defaults to development
 *   node build.js development
 *   node build.js production
 *
 * After running for production, reload the extension in chrome://extensions
 * before submitting to the Chrome Web Store.
 */

const fs   = require('fs');
const path = require('path');

const env  = process.argv[2] || 'development';
const file = path.join(__dirname, `.env.${env}`);

if (!fs.existsSync(file)) {
  console.error(`Error: ${file} not found.`);
  process.exit(1);
}

// Parse key=value lines, ignoring comments and blanks
const vars = {};
fs.readFileSync(file, 'utf8')
  .split('\n')
  .forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const [key, ...rest] = trimmed.split('=');
    vars[key.trim()] = rest.join('=').trim();
  });

const required = ['API_BASE', 'WEBSITE_URL'];
const missing  = required.filter(k => !vars[k]);
if (missing.length) {
  console.error(`Error: missing keys in .env.${env}: ${missing.join(', ')}`);
  process.exit(1);
}

const output = `// Auto-generated by build.js — do not edit directly.
// Run:  node build.js development
//       node build.js production
// Environment: ${env}

const Config = {
  API_BASE:    '${vars.API_BASE}',
  WEBSITE_URL: '${vars.WEBSITE_URL}',
};
`;

const outFile = path.join(__dirname, 'config.js');
fs.writeFileSync(outFile, output, 'utf8');
console.log(`✓ config.js written for [${env}]`);
console.log(`  API_BASE:    ${vars.API_BASE}`);
console.log(`  WEBSITE_URL: ${vars.WEBSITE_URL}`);