// Auto-generated by build.js — do not edit directly.
// Run:  node build.js development   (default)
//       node build.js production
//
// Development defaults are committed so the extension works immediately
// after `Load unpacked` without running the build script first.

const Config = {
  API_BASE:    'http://localhost:5000/api/v1',
  WEBSITE_URL: 'http://localhost:5173',
};