// Auto-generated by build.js — do not edit directly.
// Run:  node build.js development
//       node build.js production
// Environment: development

const Config = {
  API_BASE:    'http://localhost:5000/api/v1',
  WEBSITE_URL: 'http://localhost:5173',
};
